---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-viewer-deployment
  namespace: shabad-os
  labels:
    app: database-viewer
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-viewer
  template:
    metadata:
      labels:
        app: database-viewer
    spec:
      containers:
      - image: shabados/database-viewer-frontend:122fbaa9eab824a7e4d8b8305d38895ad0516f71
        name: database-viewer-frontend
        ports:
        - containerPort: 52526
          name: http
      - image: shabados/database-viewer-backend:3001c1bc8c1f107956b358aa62abcc56e63ec51b
        name: database-viewer-backend
        command: ["npm", "run", "start:production"]
        env:
        - name: PORT
          value: "52526"
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: database-viewer-service
  namespace: shabad-os
spec:
  selector:
    app: database-viewer
  ports:
  - name: backend
    port: 52526
    targetPort: 52526
  - name: frontend
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: database-viewer-ingress
  namespace: shabad-os
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: database.shabados.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: database-viewer-service
          servicePort: backend
      - path: /
        backend:
          serviceName: database-viewer-service
          servicePort: frontend
