---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment--production
  namespace: gurbani-now
  labels:
    app: web--production
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web--production
  template:
    metadata:
      labels:
        app: web--production
    spec:
      containers:
      - image: docker.pkg.github.com/gurbaninow/web/web-dev:0b35d25bce09fcc84b324f5c221738cf369ab19c
        name: web-backend--production
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: web-service--production
  namespace: gurbani-now
spec:
  selector:
    app: web--production
  ports:
  - name: backend
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web--production
  namespace: gurbani-now
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: gurbaninow.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web-service--production
          servicePort: backend
  tls:
  - secretName: gurbaninow-tls-cert
