apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: shabad-os
  labels:
    app: website
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shabados-website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: shabados/website
          name: website
          ports:
            - containerPort: 80
              name: http