apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1
spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    path: stable/traefik
    version: 1.78.2
  values:
    acme:
      enabled: "true"
      challengeType: "tls-alpn-01"
      email: "team@shabados.com"
      staging: "false"
    ssl:
      enabled: "true"
      enforced: "true"
      permanentRedirect: "true"